" General settings
syntax on
set title " Show title on X
set wildmenu " Menu has tab completion
set noautowrite " Don't automatically write on :next
set mouse= " No mouse
set ttymouse= " No mouse

" Window settings
set number " Show the line on each line

" Editing settings
set smarttab " Make tabs and backspace smarter
set autoindent " Turn on auto indenting
set expandtab " Use spaces instead of tabs
set shiftwidth=4 " Intent of 4
set tabstop=8 " Tabs of size 8 (standard)
set backspace=indent,eol,start " Allow backspacing over indent, eol, start

" Whitespace mode (Eighty Column Rule)
"highlight OverLength ctermbg=red ctermfg=white
"match OverLength /\%81v.\+/

if &diff
    colorscheme evening
endif

" Disable annoying line deletion on Ctrl+arrow keys
set term=xterm
