set tabstop=2
set shiftwidth=2
set expandtab
set number
set colorcolumn=80

" Tab inserts spaces by default per the expandtab rule above
" So if we want real tabs (e.g. in Makefile) we need to be able to.
" Shift + Tab now inserts real tabs
inoremap <S-Tab> <C-V><Tab>

syntax on
